language: node_js

node_js:
  - '8'

install:
  - npm i -g npm@5
  - npm ci

script:
  - 'npm run ci:lint'
  - 'npm run ci:test'

after_success:
  - 'npm run ci:send-coverage'

notifications:
  email: false
